sudo: required

language: python

services:
  - docker-compose

before_script:
# Let's stop postgresql
  - sudo service postgresql stop
  # wait for postgresql to shutdown
  - while sudo lsof -Pi :5432 -sTCP:LISTEN -t; do sleep 1; done
  - docker-compose build ajegugu
  - docker-compose up -d ajegugu
  - sleep 10

script:
- docker ps
- docker logs ajegugu
- docker exec -it ajegugu bash -c "pytest --cov-report term-missing --cov"

after_script:
- docker-compose stop ajegugu
