sudo: required
language: python
services:
- docker-compose
before_script:
- sudo service postgresql stop
- while sudo lsof -Pi :5432 -sTCP:LISTEN -t; do sleep 1; done
- docker-compose build web
- docker-compose up -d web
- sleep 10
script:
- docker ps
- docker logs web
after_script:
- docker-compose stop web

