sudo: required
language: python
services:
- docker-compose
before_script:
- docker-compose build
- docker-compose up -d
- sleep 10
script:
- docker ps
- docker logs web
after_script:
- docker-compose down
