version: '2'
services:
  web:
    container_name: "web"
    build: .
    working_dir: "/app"
    ports:
     - "5000:5000"
    volumes:
     - ./:/app
    depends_on:
    - database
    privileged: true
    entrypoint: bash -c "chmod 777 postgres.sh && ./postgres.sh db-todo 5432 && python manage.py db init && python manage.py db upgrade && python manage.py runserver -h=0.0.0.0 -p=5000"
  database:
    container_name: "db-todo"
    image: postgres:9
    restart: always
    env_file: .env
    expose:
      - 5432


