version: '3'

services:  
db:
    container_name: todo_db
    image: postgres
    restart: always
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
      
web:
    container_name: todo_web
    build: .
    env_file:
      - ./.env
    volumes:
      - .:/proton
    depends_on:
      - postgres
    ports:
      - "5000:5000"
    entrypoint: ["./run_web.sh"]
