version: '2'
services:
  web:
    container_name: "web"
    build: .
    working_dir: "/app"
    ports:
     - "5000:5000"
    volumes:
     - ./:/app
    depends_on:
    - db
    privileged: true
    entrypoint: bash -c "rm -rf __pycache__/ migrations/ && chmod 777 postgres.sh && ./postgres.sh db 5432 && python manage.py db init && python manage.py db migrate && python manage.py db upgrade && gunicorn -b 0.0.0.0:5000 manage:app"
  db:
    container_name: "db"
    image: postgres:9
    restart: always
    env_file: .env
    expose:
      - 5432


